sudo: false
language: go
git:
    depth: 2
install: go get -v github.com/gohugoio/hugo
script:
    ‐ hugo
deploy:
    provider: pages
    skip_cleanup: true
    github_token: $GITHUB_TOKEN
    on:
        branch: master
    local_dir: public
    repo: ltltlt/ltltlt.github.io
    target_branch: master
    email: liuty196888@gmail.com
    name: ltltlt